---
- hosts: all
  become: true
  pre_tasks:
  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: all
  become: true
  roles:
    - base
    - user
    - network
    - cgroup